"""add rag_strategy to threads

Revision ID: 4969d0d3f8ab
Revises: f247ef6836c8
Create Date: 2026-09-26 16:30:06.133215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4969d0d3f8ab'
down_revision: Union[str, Sequence[str], None] = 'f247ef6836c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('rag_strategy', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'rag_strategy')
    # ### end Alembic commands ###
