"""thread_id_uuid

Revision ID: f6f898c7a033
Revises: 90f50f85d2d5
Create Date: 2026-06-27 16:19:46.014731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6f898c7a033"
down_revision: Union[str, Sequence[str], None] = "90f50f85d2d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "thread_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=False,
    )
    op.alter_column(
        "threads", "id", existing_type=sa.INTEGER(), type_=sa.Uuid(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "threads", "id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=False
    )
    op.alter_column(
        "messages",
        "thread_id",
        existing_type=sa.Uuid(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
